version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - literacy-link
    environment:
      - GIN_MODE=release
      - Literacy_Link_Secret_Key=${Literacy_Link_Secret_Key:-default_secret_key}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - literacy-link

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${Literacy_Link_DB_ROOT_PASSWORD:-default_root_password}"
      MYSQL_DATABASE: "${Literacy_Link_DB_NAME:-default_db_name}"
      MYSQL_USER: "${Literacy_Link_DB_USERNAME:-default_username}"
      MYSQL_PASSWORD: "${Literacy_Link_DB_PASSWORD:-default_password}"
    ports:
          - "${DB_PORT:-3306}:3306"
    networks:
      - literacy-link

networks:
  literacy-link:
    driver: bridge
